version: "3"

services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - /root/personal-website/portfolio:/srv/jekyll:z
      - /root/personal-website/portfolio/vendor/bundle:/usr/local/bundle:z
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
  site:
    image: nginx
    volumes:
      - /root/personal-website/portfolio/_site:/usr/share/nginx/html:z
    ports:
      - 80:80
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
