version: "3"

services:
  build-server:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - /root/personal-website/portfolio:/srv/jekyll:z
      - /root/personal-website/portfolio/vendor/bundle:/usr/local/bundle:z
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000

  site:
    image: nginx
    volumes:
      - /root/personal-website/portfolio/_site:/usr/share/nginx/html:z
      - /etc/letsencrypt/live/map.g1y.io/fullchain.pem; # ssl_certificate managed by Certbot
      - /etc/letsencrypt/live/map.g1y.io/privkey.pem; # ssl_certificate_key managed by Certbot
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure

  certbot:
    build:
      context: ./certbot
      dockerfile: ./certbot/Dockerfile
    volumes:
      - /etc/letsencrypt/live/map.g1y.io/fullchain.pem; # ssl_certificate managed by Certbot
      - /etc/letsencrypt/live/map.g1y.io/privkey.pem; # ssl_certificate_key managed by Certbot
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
